
-- UPDATE Eras SET STANDARD_ERA = 0

-- UPDATE Eras SET ID = 9 WHERE ID = 8;
-- UPDATE Eras SET ID = 8 WHERE ID = 7;
-- UPDATE Eras SET ID = 7 WHERE ID = 6;
-- UPDATE Eras SET ID = 6 WHERE ID = 5;
-- UPDATE Eras SET ID = 5 WHERE ID = 4;
-- UPDATE Eras SET ID = 4 WHERE ID = 3;
-- UPDATE Eras SET ID = 3 WHERE ID = 2;
-- UPDATE Eras SET ID = 2 WHERE ID = 1;
-- UPDATE Eras SET ID = 1 WHERE ID = 0;


