-- Insert SQL Rules Here 
INSERT INTO Building_ResourceYieldChanges	(BuildingType,				ResourceType,				YieldType,				Yield) VALUES
											('BUILDING_TEMPLE',			'RESOURCE_ALOE_VERA',		'YIELD_GOLD',			1),
											('BUILDING_TEMPLE',			'RESOURCE_BERRIES',			'YIELD_FOOD',			1),
											('BUILDING_AMPHITHEATER',	'RESOURCE_FLAX',			'YIELD_CULTURE',		1),
											('BUILDING_FACTORY',		'RESOURCE_TITANIUM',		'YIELD_PRODUCTION',		2),
											('BUILDING_FORGE',			'RESOURCE_TIN',				'YIELD_PRODUCTION',		1),
											('BUILDING_FORGE',			'RESOURCE_MANGANESE',		'YIELD_PRODUCTION',		1),
											('BUILDING_GRANARY',		'RESOURCE_BARLEY',			'YIELD_FOOD',			1),
											('BUILDING_CARAVANSARY',	'RESOURCE_MANGO',			'YIELD_FOOD',			1),
											('BUILDING_CARAVANSARY',	'RESOURCE_TEA',				'YIELD_GOLD',			1),
											('BUILDING_CARAVANSARY',	'RESOURCE_COFFEE',			'YIELD_GOLD',			1),
											('BUILDING_CARAVANSARY',	'RESOURCE_TOBACCO',			'YIELD_GOLD',			1),
											('BUILDING_CARAVANSARY',	'RESOURCE_CACAO',			'YIELD_GOLD',			1),
											('BUILDING_GRANARY',		'RESOURCE_CORN',			'YIELD_FOOD',			1);