
UPDATE Defines SET Value=0 WHERE Name='INITIAL_CITY_POPULATION'; -- works
UPDATE Defines SET Value=0 WHERE Name='CITY_PLOTS_RADIUS';
UPDATE Defines SET Value=0 WHERE Name='CITY_PLOTS_DIAMETER';
UPDATE Defines SET Value=2 WHERE Name='NUM_CITY_PLOTS';
--MAXIMUM_ACQUIRE_PLOT_DISTANCE