-- Insert SQL Rules Here 
INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
										('IMPROVEMENT_MINE',		'RESOURCE_JADE',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_TEA',			1,					1,				0,				0),
										('IMPROVEMENT_LUMBERMILL',	'RESOURCE_OAK',			1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_WOOD',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_COFFEE',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_TIN',			1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_BERRIES',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_FARM',		'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_FARM',		'RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_MANGO',		1,					1,				0,				0);
