-- Insert SQL Rules Here 

INSERT INTO ArtDefine_LandmarkTypes (Type, LandmarkType, FriendlyName) VALUES	
									('ART_DEF_RESOURCE_COFFEE_BEANS', 'Resource', 'Coffee Tree'),
									('ART_DEF_RESOURCE_TITANIUM', 'Resource', 'Titanium'),
									('ART_DEF_RESOURCE_TITANIUM_HEAVY', 'Resource', 'Titanium Heavy'),
									('ART_DEF_RESOURCE_TITANIUM_HEAVY_MARSH', 'Resource', 'Titanium Heavy Marsh'),
									('ART_DEF_RESOURCE_TITANIUM_MARSH', 'Resource', 'Titanium Marsh'),
									('ART_DEF_RESOURCE_POPPY','Resource','Poppy'),
									('ART_DEF_RESOURCE_TOBACCO','Resource','Tobacco'),
									('ART_DEF_RESOURCE_TIN','Resource','Tin'),
									('ART_DEF_RESOURCE_ALOEVERA','Resource','Aloe Vera'),
									('ART_DEF_RESOURCE_AMBER','Resource','Amber'),
									('ART_DEF_RESOURCE_MANGANESE','Resource','Manganese'),
									('ART_DEF_RESOURCE_WOOD','Resource','Hardwood'),
									('ART_DEF_RESOURCE_OAK','Resource','Lumber'),
									('ART_DEF_RESOURCE_BERRIES','Resource','Berries'),
									('ART_DEF_RESOURCE_MANGO', 'Resource', 'Mango'),
									('ART_DEF_RESOURCE_FLAX','Resource','Flax'),
									('ART_DEF_RESOURCE_CACAO','Resource','Cacao Trees'),
									('ART_DEF_RESOURCE_BARLEY','Resource','Barley'),
									('ART_DEF_RESOURCE_TEA','Resource','Tea'),
									('ART_DEF_RESOURCE_COCONUT','Resource','Coconut'),
									('ART_DEF_RESOURCE_RUBBER','Resource','Rubber'),
									('ART_DEF_RESOURCE_LUBORIC', 'Resource', 'Jade'),
									('ART_DEF_RESOURCE_CORN','Resource','Corn');
