-- Insert SQL Rules Here 
INSERT INTO ArtDefine_StrategicView (StrategicViewType, TileType, Asset) VALUES	
									('ART_DEF_RESOURCE_COFFEE_BEANS', 'Resource', 'Additions/Art/Resources/Coffee/SV_CoffeeBean.dds'),
									('ART_DEF_RESOURCE_TITANIUM','Resource','Additions/Art/Resources/Titanium/SV_Titanium.dds'),
									('ART_DEF_RESOURCE_POPPY','Resource','Additions/Art/Resources/Poppy/SV_Poppy.dds'),
									('ART_DEF_RESOURCE_TOBACCO','Resource','Additions/Art/Resources/Tobacco/SV_Tobacco.dds'),
									('ART_DEF_RESOURCE_TIN','Resource','Additions/Art/Resources/Tin/SV_Tin.dds'),
									('ART_DEF_RESOURCE_ALOEVERA','Resource','Additions/Art/Resources/Aloe Vera/SV_Aloevera.dds'),
									('ART_DEF_RESOURCE_AMBER','Resource','Additions/Art/Resources/Amber/SV_Amber.dds'),
									('ART_DEF_RESOURCE_MANGANESE','Resource','Additions/Art/Resources/Manganese/SV_Manganese.dds'),
									('ART_DEF_RESOURCE_WOOD','Resource','Additions/Art/Resources/Wood/SV_Wood.dds'),
									('ART_DEF_RESOURCE_OAK','Resource','Additions/Art/Resources/Oak/SV_Oak.dds'),
									('ART_DEF_RESOURCE_BERRIES','Resource','Additions/Art/Resources/Berries/SV_Berries.dds'),
									('ART_DEF_RESOURCE_MANGO','Resource','Additions/Art/Resources/Mango/SV_Mango.dds'),
									('ART_DEF_RESOURCE_FLAX','Resource','Additions/Art/Resources/Flax/SV_Flax.dds'),
									('ART_DEF_RESOURCE_CACAO','Resource','Additions/Art/Resources/Cacao/SV_Cacao.dds'),
									('ART_DEF_RESOURCE_BARLEY','Resource','Additions/Art/Resources/Barley/SV_Barley.dds'),
									('ART_DEF_RESOURCE_TEA','Resource','Additions/Art/Resources/Tea/SV_Tea.dds'),
									('ART_DEF_RESOURCE_COCONUT','Resource','Additions/Art/Resources/Coconut/SV_Coconut.dds'),
									('ART_DEF_RESOURCE_RUBBER','Resource','Additions/Art/Resources/Rubber/SV_Rubber.dds'),
									('ART_DEF_RESOURCE_LUBORIC','Resource','Additions/Art/Resources/Jade/SV_Jade.dds'),
									('ART_DEF_RESOURCE_CORN','Resource','Additions/Art/Resources/Corn/SV_Corn.dds');