--
INSERT INTO ArtDefine_Landmarks (Era, State, Scale, ImprovementType, LayoutHandler, ResourceType, Model, TerrainContour) VALUES	
								-- 1 Coffee --------------------------------------------------------------------------------------------------------------
								('Any', 'Any', 0.94, 'ART_DEF_IMPROVEMENT_NONE', 'SNAPSHOT', 'ART_DEF_RESOURCE_COFFEE_BEANS', 'Additions/Art/Resources/Coffee/Resource_Coffee.fxsxml', 1),
								('Ancient', 'UnderConstruction', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_COFFEE_BEANS', 'Additions/Art/Resources/Coffee/HB_Plantation_MID_Coffee.fxsxml', 1),
								('Ancient', 'Constructed', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_COFFEE_BEANS', 'Additions/Art/Resources/Coffee/Plantation_MID_Coffee.fxsxml', 1),
								('Ancient', 'Pillaged', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_COFFEE_BEANS', 'Additions/Art/Resources/Coffee/PL_Plantation_MID_Coffee.fxsxml', 1),
								('Industrial', 'UnderConstruction', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_COFFEE_BEANS', 'Additions/Art/Resources/Coffee/HB_Plantation_IND_Coffee.fxsxml', 1),
								('Industrial', 'Constructed', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_COFFEE_BEANS', 'Additions/Art/Resources/Coffee/Plantation_IND_coffee.fxsxml', 1),
								('Industrial', 'Pillaged', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_COFFEE_BEANS', 'Additions/Art/Resources/Coffee/PL_Plantation_IND_Coffee.fxsxml', 1),
								-- 2 Titanium ---------------------------------------------------------------------------------------------------------------------------
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM','Additions/Art/Resources/Titanium/HB_MED_Mine_Titanium.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM','Additions/Art/Resources/Titanium/MED_Mine_Titanium.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM','Additions/Art/Resources/Titanium/PL_MED_Mine_Titanium.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM','Additions/Art/Resources/Titanium/HB_IND_Mine_Titanium.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM','Additions/Art/Resources/Titanium/IND_Mine_Titanium.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM','Additions/Art/Resources/Titanium/PL_IND_Mine_Titanium.fxsxml',1),
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM','Additions/Art/Resources/Titanium/Titanium.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY','Additions/Art/Resources/Titanium/HB_MED_Mine_Titanium_Heavy.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY','Additions/Art/Resources/Titanium/MED_Mine_Titanium_Heavy.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY','Additions/Art/Resources/Titanium/PL_MED_Mine_Titanium_Heavy.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY','Additions/Art/Resources/Titanium/HB_IND_Mine_Titanium_Heavy.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY','Additions/Art/Resources/Titanium/IND_Mine_Titanium_Heavy.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY','Additions/Art/Resources/Titanium/PL_IND_Mine_Titanium_Heavy.fxsxml',1),
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY','Additions/Art/Resources/Titanium/Titanium_Heavy.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY_MARSH','Additions/Art/Resources/Titanium/HB_MED_Mine_Titanium_Heavy.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY_MARSH','Additions/Art/Resources/Titanium/MED_Mine_Titanium_Heavy.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY_MARSH','Additions/Art/Resources/Titanium/PL_MED_Mine_Titanium_Heavy.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY_MARSH','Additions/Art/Resources/Titanium/HB_IND_Mine_Titanium_Heavy.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY_MARSH','Additions/Art/Resources/Titanium/IND_Mine_Titanium_Heavy.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY_MARSH','Additions/Art/Resources/Titanium/PL_IND_Mine_Titanium_Heavy.fxsxml',1),
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_HEAVY_MARSH','Additions/Art/Resources/Titanium/Titanium_Heavy_marsh.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_MARSH','Additions/Art/Resources/Titanium/HB_MED_Mine_Titanium.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_MARSH','Additions/Art/Resources/Titanium/MED_Mine_Titanium.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_MARSH','Additions/Art/Resources/Titanium/PL_MED_Mine_Titanium.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_MARSH','Additions/Art/Resources/Titanium/HB_IND_Mine_Titanium.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_MARSH','Additions/Art/Resources/Titanium/IND_Mine_Titanium.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_MARSH','Additions/Art/Resources/Titanium/PL_IND_Mine_Titanium.fxsxml',1),
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_TITANIUM_MARSH','Additions/Art/Resources/Titanium/Titanium_marsh.fxsxml',1),
								-- 3 Poppy ----------------------------------------------------------------------------------------------------------------------
								('Any','Any',0.94,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_POPPY','Additions/Art/Resources/Poppy/MAX_File/Resource_Poppy.fxsxml',1),
								('Ancient','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_POPPY','Additions/Art/Resources/Poppy/HB_Plantation_MID_Poppy.fxsxml',1),
								('Ancient','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_POPPY','Additions/Art/Resources/Poppy/Plantation_MID_Poppy.fxsxml',1),
								('Ancient','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_POPPY','Additions/Art/Resources/Poppy/PL_Plantation_MID_Poppy.fxsxml',1),
								('Industrial','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_POPPY','Additions/Art/Resources/Poppy/HB_Plantation_IND_Poppy.fxsxml',1),
								('Industrial','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_POPPY','Additions/Art/Resources/Poppy/Plantation_IND_Poppy.fxsxml',1),
								('Industrial','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_POPPY','Additions/Art/Resources/Poppy/PL_Plantation_IND_Poppy.fxsxml',1),
								-- 4 Tobacco -------------------------------------------------------------------------------------------------------------------------
								('Any','Any',0.98,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_TOBACCO','Additions/Art/Resources/Tobacco/Resource_Tobacco.fxsxml',1),
								('Ancient','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TOBACCO','Additions/Art/Resources/Tobacco/HB_Plantation_MID_Tobacco.fxsxml',1),
								('Ancient','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TOBACCO','Additions/Art/Resources/Tobacco/Plantation_MID_Tobacco.fxsxml',1),
								('Ancient','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TOBACCO','Additions/Art/Resources/Tobacco/PL_Plantation_MID_Tobacco.fxsxml',1),
								('Industrial','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TOBACCO','Additions/Art/Resources/Tobacco/HB_Plantation_IND_Tobacco.fxsxml',1),
								('Industrial','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TOBACCO','Additions/Art/Resources/Tobacco/Plantation_IND_Tobacco.fxsxml',1),
								('Industrial','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TOBACCO','Additions/Art/Resources/Tobacco/PL_Plantation_IND_Tobacco.fxsxml',1),
								-- 5 Tin ----------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_TIN','Additions/Art/Resources/Tin/Tin.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TIN','Additions/Art/Resources/Tin/HB_MED_Tin_Mine.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TIN','Additions/Art/Resources/Tin/MED_Mine_Tin.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TIN','Additions/Art/Resources/Tin/PL_MED_Mine_Tin.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TIN','Additions/Art/Resources/Tin/HB_IND_Tin_Mine.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TIN','Additions/Art/Resources/Tin/IND_Mine_Tin.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_TIN','Additions/Art/Resources/Tin/PL_MED_Mine_Tin.fxsxml',1),
								-- 6 Aloe Vera -----------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any','0.94','ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_ALOEVERA','Additions/Art/Resources/Aloe Vera/Resource_Aloevera.fxsxml',1),
								('Ancient','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_ALOEVERA','Additions/Art/Resources/Aloe Vera/HB_Plantation_MID_Aloevera.fxsxml',1),
								('Ancient','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_ALOEVERA','Additions/Art/Resources/Aloe Vera/Plantation_MID_Aloevera.fxsxml',1),
								('Ancient','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_ALOEVERA','Additions/Art/Resources/Aloe Vera/PL_Plantation_MID_Aloevera.fxsxml',1),
								('Industrial','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_ALOEVERA','Additions/Art/Resources/Aloe Vera/HB_Plantation_IND_Aloevera.fxsxml',1),
								('Industrial','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_ALOEVERA','Additions/Art/Resources/Aloe Vera/Plantation_IND_Aloevera.fxsxml',1),
								('Industrial','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_ALOEVERA','Additions/Art/Resources/Aloe Vera/PL_Plantation_IND_Aloevera.fxsxml',1),
								-- 7 Amber ---------------------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_AMBER','Additions/Art/Resources/Amber/Amber.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_AMBER','Additions/Art/Resources/Amber/HB_MED_Amber_Mine.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_AMBER','Additions/Art/Resources/Amber/MED_Mine_Amber.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_AMBER','Additions/Art/Resources/Amber/PL_MED_Mine_Amber.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_AMBER','Additions/Art/Resources/Amber/HB_IND_Amber_Mine.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_AMBER','Additions/Art/Resources/Amber/IND_Mine_Amber.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_AMBER','Additions/Art/Resources/Amber/PL_MED_Mine_Amber.fxsxml',1),
								-- 8 Manganese --------------------------------------------------------------------------------------------------------------------------------------------------
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_MANGANESE','Additions/Art/Resources/Manganese/HB_MED_Mine_Manganese.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_MANGANESE','Additions/Art/Resources/Manganese/MED_Mine_Manganese.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_MANGANESE','Additions/Art/Resources/Manganese/PL_MED_Mine_Manganese.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_MANGANESE','Additions/Art/Resources/Manganese/HB_IND_Mine_Manganese.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_MANGANESE','Additions/Art/Resources/Manganese/IND_Mine_Manganese.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_MANGANESE','Additions/Art/Resources/Manganese/PL_IND_Mine_Manganese.fxsxml',1),
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_MANGANESE','Additions/Art/Resources/Manganese/Manganese.fxsxml',1),
								-- 9 Exotic Wood -------------------------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_WOOD','Additions/Art/Resources/Wood/Resource_Wood.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_WOOD','Additions/Art/Resources/Wood/HB_Plantation_MID_Wood.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_WOOD','Additions/Art/Resources/Wood/Plantation_MID_Wood.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_WOOD','Additions/Art/Resources/Wood/PL_Plantation_MID_Wood.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_WOOD','Additions/Art/Resources/Wood/HB_Plantation_IND_Wood.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_WOOD','Additions/Art/Resources/Wood/Plantation_IND_Wood.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_WOOD','Additions/Art/Resources/Wood/PL_Plantation_IND_Wood.fxsxml',1),
								-- 10 Oak ---------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_OAK','Additions/Art/Resources/Oak/Resource_Oak.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_OAK','Additions/Art/Resources/Oak/HB_Plantation_MID_Oak.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_OAK','Additions/Art/Resources/Oak/Plantation_MID_Oak.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_OAK','Additions/Art/Resources/Oak/PL_Plantation_MID_Oak.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_OAK','Additions/Art/Resources/Oak/HB_Plantation_IND_Oak.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_OAK','Additions/Art/Resources/Oak/Plantation_IND_Oak.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_OAK','Additions/Art/Resources/Oak/PL_Plantation_IND_Oak.fxsxml',1),
								-- 11 Berries ---------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_BERRIES','Additions/Art/Resources/Berries/Resource_Berries.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_BERRIES','Additions/Art/Resources/Berries/HB_Plantation_MID_Berries.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_BERRIES','Additions/Art/Resources/Berries/Plantation_MID_Berries.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_BERRIES','Additions/Art/Resources/Berries/PL_Plantation_MID_Berries.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_BERRIES','Additions/Art/Resources/Berries/HB_Plantation_IND_Berries.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_BERRIES','Additions/Art/Resources/Berries/Plantation_IND_Berries.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_BERRIES','Additions/Art/Resources/Berries/PL_Plantation_IND_Berries.fxsxml',1),
								-- 12 Mango ---------------------------------------------------------------------------------------------------------------------------------------
								('Any', 'Any', 0.94, 'ART_DEF_IMPROVEMENT_NONE', 'SNAPSHOT', 'ART_DEF_RESOURCE_MANGO', 'Additions/Art/Resources/Mango/Resource_Mango.fxsxml', 1),
								('Ancient', 'UnderConstruction', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_MANGO', 'Additions/Art/Resources/Mango/HB_Plantation_MID_Mango.fxsxml', 1),
								('Ancient', 'Constructed', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_MANGO', 'Additions/Art/Resources/Mango/Plantation_MID_Mango.fxsxml', 1),
								('Ancient', 'Pillaged', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_MANGO', 'Additions/Art/Resources/Mango/PL_Plantation_MID_Mango.fxsxml', 1),
								('Industrial', 'UnderConstruction', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_MANGO', 'Additions/Art/Resources/Mango/HB_Plantation_IND_Mango.fxsxml', 1),
								('Industrial', 'Constructed', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_MANGO', 'Additions/Art/Resources/Mango/Plantation_IND_Mango.fxsxml', 1),
								('Industrial', 'Pillaged', 0.96, 'ART_DEF_IMPROVEMENT_PLANTATION', 'SNAPSHOT', 'ART_DEF_RESOURCE_MANGO', 'Additions/Art/Resources/Mango/PL_Plantation_IND_Mango.fxsxml', 1),
								-- 13 Flax ---------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',0.94,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_FLAX','Additions/Art/Resources/Flax/Resource_Flax.fxsxml',1),
								('Ancient','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_FLAX','Additions/Art/Resources/Flax/HB_Plantation_MID_Flax.fxsxml',1),
								('Ancient','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_FLAX','Additions/Art/Resources/Flax/Plantation_MID_Flax.fxsxml',1),
								('Ancient','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_FLAX','Additions/Art/Resources/Flax/PL_Plantation_MID_Flax.fxsxml',1),
								('Industrial','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_FLAX','Additions/Art/Resources/Flax/HB_Plantation_IND_Flax.fxsxml',1),
								('Industrial','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_FLAX','Additions/Art/Resources/Flax/Plantation_IND_Flax.fxsxml',1),
								('Industrial','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_FLAX','Additions/Art/Resources/Flax/PL_Plantation_IND_Flax.fxsxml',1),
								-- 14 Cacao ---------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',0.94,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_CACAO','Additions/Art/Resources/Cacao/Cacao.fxsxml',1),
								('Ancient','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_CACAO','Additions/Art/Resources/Cacao/Plantation_MID_Cacao_HB.fxsxml',1),
								('Ancient','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_CACAO','Additions/Art/Resources/Cacao/Plantation_MID_Cacao.fxsxml',1),
								('Ancient','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_CACAO','Additions/Art/Resources/Cacao/Plantation_MID_Cacao_PIL.fxsxml',1),
								('Industrial','UnderConstruction',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_CACAO','Additions/Art/Resources/Cacao/Plantation_IND_Cacao_HB.fxsxml',1),
								('Industrial','Constructed',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_CACAO','Additions/Art/Resources/Cacao/Plantation_IND_Cacao.fxsxml',1),
								('Industrial','Pillaged',0.96,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_CACAO','Additions/Art/Resources/Cacao/Plantation_IND_Cacao_PIL.fxsxml',1),
								-- 15 Barley ---------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',0.75,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_BARLEY','Additions/Art/Resources/Barley/Resource_Barley.fxsxml',1),
								--('Any', 'UnderConstruction',	0.9,  'ART_DEF_IMPROVEMENT_FARM',	'SNAPSHOT',			'ART_DEF_RESOURCE_BARLEY',	'Additions/Art/Improvements/Farms/HBfarmfix01.fxsxml',	1 ),
								--('Any', 'Constructed',			0.9,  'ART_DEF_IMPROVEMENT_FARM',	'SNAPSHOT',			'ART_DEF_RESOURCE_BARLEY',	'Additions/Art/Improvements/Farms/farmwheat01.fxsxml',	1 ),
								--('Any', 'Pillaged',				0.9,  'ART_DEF_IMPROVEMENT_FARM',	'SNAPSHOT',			'ART_DEF_RESOURCE_BARLEY',	'Additions/Art/Improvements/Farms/PLfarmfix01.fxsxml',	1 ),
								-- 16 Tea ---------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any','0.7399999976158142','ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_TEA','Additions/Art/Resources/Tea/Resource_Tea.fxsxml',1),
								('Ancient','UnderConstruction','0.7599999785423279','ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TEA','Additions/Art/Resources/Tea/HB_Plantation_MID_Tea.fxsxml',1),
								('Ancient','Constructed','0.7599999785423279','ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TEA','Additions/Art/Resources/Tea/Plantation_MID_Tea.fxsxml',1),
								('Ancient','Pillaged','0.7599999785423279','ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TEA','Additions/Art/Resources/Tea/PL_Plantation_MID_Tea.fxsxml',1),
								('Industrial','UnderConstruction','0.7599999785423279','ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TEA','Additions/Art/Resources/Tea/HB_Plantation_IND_Tea.fxsxml',1),
								('Industrial','Constructed','0.7599999785423279','ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TEA','Additions/Art/Resources/Tea/Plantation_IND_Tea.fxsxml',1),
								('Industrial','Pillaged','0.7599999785423279','ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_TEA','Additions/Art/Resources/Tea/PL_Plantation_IND_Tea.fxsxml',1),
								-- 17 Coconut -------------------------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_COCONUT','Additions/Art/Resources/Coconut/Resource_Coconut.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_COCONUT','Additions/Art/Resources/Coconut/HB_Plantation_MID_Coconut.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_COCONUT','Additions/Art/Resources/Coconut/Plantation_MID_Coconut.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_COCONUT','Additions/Art/Resources/Coconut/PL_Plantation_MID_Coconut.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_COCONUT','Additions/Art/Resources/Coconut/HB_Plantation_IND_Coconut.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_COCONUT','Additions/Art/Resources/Coconut/Plantation_IND_Coconut.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_COCONUT','Additions/Art/Resources/Coconut/PL_Plantation_IND_Coconut.fxsxml',1),
								-- 18 Rubber -------------------------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',1,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_RUBBER','Additions/Art/Resources/Rubber/Resource_Rubber.fxsxml',1),
								('Ancient','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_RUBBER','Additions/Art/Resources/Rubber/HB_Plantation_MID_Rubber.fxsxml',1),
								('Ancient','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_RUBBER','Additions/Art/Resources/Rubber/Plantation_MID_Rubber.fxsxml',1),
								('Ancient','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_RUBBER','Additions/Art/Resources/Rubber/PL_Plantation_MID_Rubber.fxsxml',1),
								('Industrial','UnderConstruction',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_RUBBER','Additions/Art/Resources/Rubber/HB_Plantation_IND_Rubber.fxsxml',1),
								('Industrial','Constructed',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_RUBBER','Additions/Art/Resources/Rubber/Plantation_IND_Rubber.fxsxml',1),
								('Industrial','Pillaged',1,'ART_DEF_IMPROVEMENT_PLANTATION','SNAPSHOT','ART_DEF_RESOURCE_RUBBER','Additions/Art/Resources/Rubber/PL_Plantation_IND_Rubber.fxsxml',1),
								-- 19 Jade -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',1.0,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_LUBORIC','Additions/Art/Resources/Jade/luboric.fxsxml',1),
								('Ancient','UnderConstruction',1.0,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_LUBORIC','Additions/Art/Resources/Jade/hb_med_luboric_mine.fxsxml',1),
								('Ancient','Constructed',1.0,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_LUBORIC','Additions/Art/Resources/Jade/med_mine_luboric.fxsxml',1),
								('Ancient','Pillaged',1.0,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_LUBORIC','Additions/Art/Resources/Jade/pl_med_mine_luboric.fxsxml',1),
								('Industrial','UnderConstruction',1.0,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_LUBORIC','Additions/Art/Resources/Jade/hb_ind_luboric_mine.fxsxml',1),
								('Industrial','Constructed',1.0,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_LUBORIC','Additions/Art/Resources/Jade/ind_mine_luboric.fxsxml',1),
								('Industrial','Pillaged',1.0,'ART_DEF_IMPROVEMENT_MINE','SNAPSHOT','ART_DEF_RESOURCE_LUBORIC','Additions/Art/Resources/Jade/pl_ind_mine_luboric.fxsxml',1),
								-- 20 Corn -----------------------------------------------------------------------------------------------------------------------------------------
								('Any','Any',0.75,'ART_DEF_IMPROVEMENT_NONE','SNAPSHOT','ART_DEF_RESOURCE_CORN','Additions/Art/Resources/Corn/Resource_Corn.fxsxml',1);
								--('Any', 'UnderConstruction',	0.9,  'ART_DEF_IMPROVEMENT_FARM',	'SNAPSHOT',			'ART_DEF_RESOURCE_CORN',	'Additions/Art/Improvements/Farms/HBfarmfix02.fxsxml',	1 ),
								--('Any', 'Constructed',			0.9,  'ART_DEF_IMPROVEMENT_FARM',	'SNAPSHOT',			'ART_DEF_RESOURCE_CORN',	'Additions/Art/Improvements/Farms/farmwheat02.fxsxml',	1 ),
								--('Any', 'Pillaged',				0.9,  'ART_DEF_IMPROVEMENT_FARM',	'SNAPSHOT',			'ART_DEF_RESOURCE_CORN',	'Additions/Art/Improvements/Farms/PLfarmfix02.fxsxml',	1 );
