--[[


╔═════════════════════════════════════════════════════════════════════════════
║
║  PLAYER
║  
╠═════════════════════════════════════════════════════════════════════════════
║
║
║
║
║
║
║
║
║
║
║
║
║
║
║
║
║
║
║
║
║
║ RIGHTS
║
║ Release under GPLV3 as per some of the original GPLV3 code
║
║
║
║
╚═════════════════════════════════════════════════════════════════════════════


player:Cities()



--]]



logger.PREFIX = "player"

logger:info( "" )
logger:info( "__FILE__ Player_Pre" )





data = {}




GameEvents.PlayerDoTurn.Add(function(iPlayer) 

  logger:debug( "[PlayerDoTurn]" )

  local pPlayer =     Players[iPlayer]
  local bIsHuman =    pPlayer:IsHuman()
  local iHappiness =  pPlayer:GetExcessHappiness()
  local iTotalGold =  pPlayer:GetGold()
  local pCapital =    pPlayer:GetCapitalCity()

  local iTurn =       Game:GetGameTurn()


  if ( iTurn == 5 ) then -- TODO: remove hard-coded number into global options
    logger:debug( "free unit adding..." )
    pPlayer:AddFreeUnit (GameInfo.Units["UNIT_TMP_TREE_SETTLER"].ID, UNITAI_SETTLE)

  end





end); -- PlayerDoTurn







--
-- PlayerLoop
--
-- (Thank you IGE -- took most of funtion from IGE "SetPlayersData")
--
function PlayerInfoLoop( options )
  if data.playersByID then return end
  data.playersByCivType = {}
  data.playersByID =      {}
  data.minorPlayers =     {}
  data.majorPlayers =     {}
  data.allPlayers =       {}

  for i = 0, GameDefines.MAX_CIV_PLAYERS, 1 do
    local player = Players[i]
    if player:IsEverAlive() then -- Must check it to prevent a crash
      -- player.info = {}
      local player_info =       {}
      local player_civ =        {}
      player_info.civ_type =    player:GetCivilizationType()
      player_info.civ =         GameInfo.Civilizations[player_info.civ_type]
      player_info.civname =     player_info.civ.ShortDescription

      if player.isCityState then

        -- todo

      else -- not city state
        player_info.name =        player:GetName()
        player_info.type =        player:GetLeaderType();
        player_info.leaderType =  player:GetLeaderType();
        player_info.isBarbarian = (i == GameDefines.MAX_CIV_PLAYERS)


      end -- city state test

    end
  end


end




--
-- PlayerIsCityState
--
function PlayerIsCityState( pPlayer )

  pPlayer.isCityState = (i >= GameDefines.MAX_MAJOR_CIVS) and (i < GameDefines.MAX_CIV_PLAYERS);

end


-- SAVE DATA
-- save(pPlayer,{"table key"},"value");
   -- for k,v in pairs(load(pPlayer)) do














--[[

╔═════════════════════════════════════════════════════════════════════════════
║
║ PLAYER INSTANCE METHODS
║
║ extracted 2014-05-30
║ 788 methods
║
╚═════════════════════════════════════════════════════════════════════════════


AcquireCity
AddCityName
AddFreeUnit
AddMinorCivQuestIfAble
AddNotification
AddTemporaryDominanceZone
AI_foundValue
AI_updateFoundValues
CalculateGoldRate
CalculateGoldRateTimes100
CalculateGrossGold
CalculateGrossGoldTimes100
CalculateInflatedCosts
CalculateResearchModifier
CalculateTotalYield
CalculateUnitCost
CalculateUnitSupply
CanAdoptPolicy
CanBuild
CanCommitVote
CanConstruct
CanCreate
CanCreatePantheon
CanEverResearch
CanFound
CanGetGoody
CanMaintain
CanMajorBullyGold
CanMajorBullyUnit
CanMajorBuyout
CanMajorGiftTileImprovement
CanMajorGiftTileImprovementAtPlot
CanMajorProtect
CanMajorStartProtection
CanMajorWithdrawProtection
CanPrepare
CanRaze
CanReceiveGoody
CanResearch
CanResearchForFree
CanSpyStageCoup
CanTrain
CanUnlockPolicyBranch
ChangeAdvancedStartPoints
ChangeAlwaysSeeBarbCampsCount
ChangeAnarchyNumTurns
ChangeBarbarianCombatBonus
ChangeBaseBuildingGoldMaintenance
ChangeCombatExperience
ChangeConscriptCount
ChangeExtraHappinessPerCity
ChangeFaith
ChangeFreePromotionCount
ChangeGarrisonedCityRangeStrikeModifier
ChangeGold
ChangeGoldenAgeProgressMeter
ChangeGoldenAgeTurns
ChangeGoldPerUnitTimes100
ChangeHappinessPerGarrisonedUnit
ChangeHappinessPerTradeRoute
ChangeJONSCulture
ChangeJONSCulturePerTurnForFree
ChangeJONSCulturePerTurnFromMinorCivs
ChangeMinorCivFriendshipWithMajor
ChangeNavalCombatExperience
ChangeNewCityExtraPopulation
ChangeNumFaithGreatPeople
ChangeNumFreeGreatPeople
ChangeNumFreePolicies
ChangeNumFreeTenets
ChangeNumGoldenAges
ChangeNumMayaBoosts
ChangeNumPlotsBought
ChangeNumResourceTotal
ChangeNumUnitGoldenAges
ChangeNumWorldWonders
ChangeScoreFromFutureTech
ChangeScoreFromScenario1
ChangeScoreFromScenario2
ChangeScoreFromScenario3
ChangeScoreFromScenario4
ChangeUnhappinessFromUnits
ChooseTech
Cities
ClearResearchQueue
CountCityFeatures
CountNumBuildings
CreateGreatGeneral
Disband
DisbandUnit
DoAdoptPolicy
DoBeginDiploWithHuman
DoesUnitPassFaithPurchaseCheck
DoForceDenounce
DoForceDoF
DoGoody
DoMinorLiberationByMajor
DoTradeScreenClosed
DoTradeScreenOpened
DoUpdateProximityToPlayer
FindNewCapital
FindPathLength
Found
GetActiveQuestForPlayer
GetAdvancedStartBuildingCost
GetAdvancedStartCityCost
GetAdvancedStartImprovementCost
GetAdvancedStartPoints
GetAdvancedStartPopCost
GetAdvancedStartRouteCost
GetAdvancedStartTechCost
GetAdvancedStartUnitCost
GetAdvancedStartVisibilityCost
GetAgricultureHistory
GetAlliedTurns
GetAlly
GetAnarchyNumTurns
GetAnyUnitHasOrderToGoody
GetApproachTowardsUsGuess
GetArtStyleType
GetAttackBonusTurns
GetAvailableSpyRelocationCities
GetAvailableTenets
GetAveragePopulation
GetBarbarianCombatBonus
GetBeliefInPantheon
GetBestRoute
GetBranchPicked1
GetBranchPicked2
GetBranchPicked3
GetBuildingClassCount
GetBuildingClassCountPlusMaking
GetBuildingClassMaking
GetBuildingClassPrereqBuilding
GetBuildingGoldMaintenance
GetBuildingOfClosestGreatWorkSlot
GetBuildingProductionModifier
GetBuildingProductionNeeded
GetBuyoutCost
GetBuyPlotCost
GetCapitalCity
GetCapitalSettlerProductionModifier
GetCapitalUnhappinessMod
GetCapitalYieldRateModifier
GetCitiesLost
GetCityByID
GetCityConnectionGold
GetCityConnectionGoldTimes100
GetCityConnectionRouteGoldTimes100
GetCityConnectionTradeRouteGoldModifier
GetCityCountUnhappinessMod
GetCityDefenseModifier
GetCityName
GetCityOfClosestGreatWorkSlot
GetCivilizationAdjective
GetCivilizationAdjectiveKey
GetCivilizationDescription
GetCivilizationDescriptionKey
GetCivilizationShortDescription
GetCivilizationShortDescriptionKey
GetCivilizationType
GetClosestGoodyPlot
GetCombatBonusVsHigherTech
GetCombatBonusVsLargerCiv
GetCombatExperience
GetCommitVoteDetails
GetCommonFoeValue
GetConscriptCount
GetConversionTimer
GetCoopWarAcceptedState
GetCoupChanceOfSuccess
GetCultureBombTimer
GetCultureBonusTurns
GetCultureCityModifier
GetCulturePerTurnFromBonusTurns
GetCulturePerTurnFromMinor
GetCulturePerTurnFromMinorCivs
GetCulturePerTurnFromReligion
GetCultureWonderMultiplier
GetCurrentCapitalFoodBonus
GetCurrentCultureBonus
GetCurrentEra
GetCurrentOtherCityFoodBonus
GetCurrentResearch
GetCurrentScienceFriendshipBonusTimes100
GetCurrentSpawnEstimate
GetDealMyValue
GetDealTheyreValue
GetDealValue
GetDenouncedPlayerCounter
GetDoFCounter
GetDomesticGreatGeneralRateModifier
GetDominantPolicyBranchForTitle
GetEconomyHistory
GetEmbarkedGraphicOverride
GetEndTurnBlockingNotificationIndex
GetEndTurnBlockingType
GetEspionageCityStatus
GetEspionageSpies
GetEverPoppedGoody
GetEverTrainedBuilder
GetExcessHappiness
GetExpInBorderModifier
GetExtraBuildingHappinessFromPolicies
GetExtraHappinessPerCity
GetExtraHappinessPerLuxury
GetExtraUnitCost
GetExtraYieldThreshold
GetFaith
GetFaithPerTurnFromCities
GetFaithPerTurnFromMinorCivs
GetFaithPerTurnFromReligion
GetFaithPurchaseIndex
GetFaithPurchaseType
GetFeatureProductionModifier
GetFirstReadyUnit
GetFirstReadyUnitPlot
GetFoundedReligionEnemyCityCombatMod
GetFoundedReligionFriendlyCityCombatMod
GetFreeExperience
GetFreePromotionCount
GetFriendshipChangePerTurnTimes100
GetFriendshipFromGoldGift
GetFriendshipFromUnitGift
GetFriendshipNeededForNextLevel
GetGarrisonedCityRangeStrikeModifier
GetGiftTileImprovementCost
GetGold
GetGoldenAgeGreatArtistRateModifier
GetGoldenAgeGreatMusicianRateModifier
GetGoldenAgeGreatWriterRateModifier
GetGoldenAgeLength
GetGoldenAgeModifier
GetGoldenAgeProgressMeter
GetGoldenAgeProgressThreshold
GetGoldenAgeTourismModifier
GetGoldenAgeTurns
GetGoldFromCitiesMinusTradeRoutesTimes100
GetGoldFromCitiesTimes100
GetGoldPerMilitaryUnit
GetGoldPerTurnFromDiplomacy
GetGoldPerTurnFromReligion
GetGoldPerTurnFromTradeRoutes
GetGoldPerTurnFromTradeRoutesTimes100
GetGoldPerTurnFromTraits
GetGoldPerUnit
GetGreatAdmiralsThresholdModifier
GetGreatArtistRateModifier
GetGreatEngineerRateModifier
GetGreatGeneralCombatBonus
GetGreatGeneralRateModifier
GetGreatGeneralsCreated
GetGreatGeneralsThresholdModifier
GetGreatMerchantRateModifier
GetGreatMusicianRateModifier
GetGreatPeopleCreated
GetGreatPeopleRateModifier
GetGreatPeopleThresholdModifier
GetGreatScientistRateModifier
GetGreatWorks
GetGreatWriterRateModifier
GetHandicapType
GetHappiness
GetHappinessFromBuildings
GetHappinessFromCities
GetHappinessFromLeagues
GetHappinessFromLuxury
GetHappinessFromMinor
GetHappinessFromMinorCivs
GetHappinessFromNaturalWonders
GetHappinessFromPolicies
GetHappinessFromReligion
GetHappinessFromResources
GetHappinessFromResourceVariety
GetHappinessFromTradeRoutes
GetHappinessPerGarrisonedUnit
GetHappinessPerTradeRoute
GetHappyPerMilitaryUnit
GetHighestUnitLevel
GetHurryCount
GetHurryGoldCost
GetHurryModifier
GetID
GetImprovementCount
GetImprovementGoldMaintenance
GetImprovementUpgradeRate
GetImprovementUpgradeRateModifier
GetIncomingUnitCountdown
GetIncomingUnitType
GetIndustryHistory
GetInfluenceCityStateSpyRankBonus
GetInfluenceLevel
GetInfluenceMajorCivSpyRankBonus
GetInfluenceOn
GetInfluencePerTurn
GetInfluenceSpyRankTooltip
GetInfluenceTradeRouteScienceBonus
GetInfluenceTrend
GetInternationalTradeRouteBaseBonus
GetInternationalTradeRouteDomainModifier
GetInternationalTradeRouteExclusiveBonus
GetInternationalTradeRouteGPTBonus
GetInternationalTradeRouteOtherTraitBonus
GetInternationalTradeRoutePlotMouseoverToolTip
GetInternationalTradeRoutePlotToolTip
GetInternationalTradeRoutePolicyBonus
GetInternationalTradeRouteResourceBonus
GetInternationalTradeRouteResourceTraitModifier
GetInternationalTradeRouteRiverModifier
GetInternationalTradeRouteScience
GetInternationalTradeRouteTheirBuildingBonus
GetInternationalTradeRouteTotal
GetInternationalTradeRouteYourBuildingBonus
GetIntrigueMessages
GetJONSCulture
GetJONSCultureEverGenerated
GetJONSCulturePerTurnForFree
GetJONSCulturePerTurnFromCities
GetJONSCulturePerTurnFromExcessHappiness
GetJONSCulturePerTurnFromMinorCivs
GetJONSCulturePerTurnFromTraits
GetLandDisputeLevel
GetLastTurnInfluenceOn
GetLastTurnLifetimeCulture
GetLateGamePolicyTree
GetLeaderType
GetLengthResearchQueue
GetLevelExperienceModifier
GetLiberationPreviewString
GetLifetimeCombatExperience
GetLifetimeGrossGold
GetMajorBullyGoldDetails
GetMajorBullyUnitDetails
GetMajorCivApproach
GetMaxConscript
GetMaxGlobalBuildingProductionModifier
GetMaxPlayerBuildingProductionModifier
GetMaxTeamBuildingProductionModifier
GetMayaCalendarLongString
GetMayaCalendarString
GetMilitaryMight
GetMilitaryProductionModifier
GetMinimumFaithNextGreatProphet
GetMinorCivBullyGoldAmount
GetMinorCivContestValueForLeader
GetMinorCivContestValueForPlayer
GetMinorCivCultureFriendshipBonus
GetMinorCivCurrentCultureBonus
GetMinorCivCurrentCultureFlatBonus
GetMinorCivCurrentCulturePerBuildingBonus
GetMinorCivCurrentFaithBonus
GetMinorCivCurrentHappinessBonus
GetMinorCivCurrentHappinessFlatBonus
GetMinorCivCurrentHappinessPerLuxuryBonus
GetMinorCivDisputeLevel
GetMinorCivFavoriteMajor
GetMinorCivFriendshipAnchorWithMajor
GetMinorCivFriendshipLevelWithMajor
GetMinorCivFriendshipWithMajor
GetMinorCivHappinessFriendshipBonus
GetMinorCivNumActiveQuestsForPlayer
GetMinorCivNumDisplayedQuestsForPlayer
GetMinorCivScienceFriendshipBonus
GetMinorCivTrait
GetMinorCivType
GetMinorCivUniqueUnit
GetMinorWarQuestWithMajorRemainingCount
GetName
GetNameKey
GetNaturalWonderYieldModifier
GetNavalCombatExperience
GetNegativeArchaeologyPoints
GetNegativeReligiousConversionPoints
GetNewCityExtraPopulation
GetNewCityName
GetNextCity
GetNextDigCompletePlot
GetNextPolicyCost
GetNickName
GetNotificationDismissed
GetNotificationIndex
GetNotificationStr
GetNotificationSummaryStr
GetNotificationTurn
GetNumAvailableTradeUnits
GetNumCities
GetNumCityNames
GetNumCiviliansReturnedToMe
GetNumCivsInfluentialOn
GetNumCivsToBeInfluentialOn
GetNumFaithGreatPeople
GetNumFreeGreatPeople
GetNumFreePolicies
GetNumFreeTechs
GetNumFreeTenets
GetNumFriendsDenouncedBy
GetNumGoldenAges
GetNumGreatWorks
GetNumGreatWorkSlots
GetNumInternationalTradeRoutesAvailable
GetNumInternationalTradeRoutesUsed
GetNumLandmarksBuiltForMe
GetNumMaintenanceFreeUnits
GetNumMayaBoosts
GetNumMilitaryUnits
GetNumMinorCivsMet
GetNumNotifications
GetNumNukeUnits
GetNumOutsideUnits
GetNumPlots
GetNumPlotsBought
GetNumPolicies
GetNumPoliciesInBranch
GetNumPolicyBranchesAllowed
GetNumPolicyBranchesFinished
GetNumPolicyBranchesUnlocked
GetNumResourceAvailable
GetNumResourceTotal
GetNumResourceUsed
GetNumSpies
GetNumTechDifference
GetNumTechsToSteal
GetNumTimesCultureBombed
GetNumTimesIntrigueSharedBy
GetNumTimesRobbedBy
GetNumUnassignedSpies
GetNumUnitGoldenAges
GetNumUnits
GetNumUnitsOutOfSupply
GetNumUnitsSupplied
GetNumUnitsSuppliedByCities
GetNumUnitsSuppliedByHandicap
GetNumUnitsSuppliedByPopulation
GetNumWarsFought
GetNumWondersBeatenTo
GetNumWorldWonders
GetOccupiedPopulationUnhappinessMod
GetOpinionTable
GetOtherPlayerNumProtectedMinorsAttacked
GetOtherPlayerNumProtectedMinorsKilled
GetOthersGreatWorks
GetOverflowResearch
GetPersonality
GetPersonalityType
GetPlayerBuildingClassHappiness
GetPlayerBuildingClassYieldChange
GetPlayerColor
GetPlayerColors
GetPlayerVisiblePlot
GetPlotDanger
GetPlotHasOrder
GetPolicyBranchChosen
GetPolicyBuildingClassYieldChange
GetPolicyBuildingClassYieldModifier
GetPolicyCatchSpiesModifier
GetPolicyEspionageCatchSpiesModifier
GetPolicyEspionageModifier
GetPolicyGreatArtistRateModifier
GetPolicyGreatEngineerRateModifier
GetPolicyGreatMerchantRateModifier
GetPolicyGreatMusicianRateModifier
GetPolicyGreatPeopleRateModifier
GetPolicyGreatScientistRateModifier
GetPolicyGreatWriterRateModifier
GetPotentialAdmiralNewPort
GetPotentialInternationalTradeRouteDestinations
GetPotentialTradeUnitNewHomeCity
GetPower
GetPowerHistory
GetPrevCity
GetProductionModifier
GetProjectProductionModifier
GetProjectProductionNeeded
GetProximityToPlayer
GetPublicOpinionPreferredIdeology
GetPublicOpinionTooltip
GetPublicOpinionType
GetPublicOpinionUnhappiness
GetPublicOpinionUnhappinessTooltip
GetQuestData1
GetQuestData2
GetQuestTurnsRemaining
GetQueuePosition
GetRealPopulation
GetRecentAssistValue
GetRecentIntrigueInfo
GetRecentTradeValue
GetRecommendedFoundCityPlots
GetRecommendedWorkerPlots
GetReligionCreatedByPlayer
GetReplayData
GetResearchCost
GetResearchProgress
GetResearchTurnsLeft
GetResourceExport
GetResourceFromMinors
GetResourceImport
GetScience
GetScienceFromBudgetDeficitTimes100
GetScienceFromCitiesTimes100
GetScienceFromHappinessTimes100
GetScienceFromOtherPlayersTimes100
GetScienceFromResearchAgreementsTimes100
GetScienceTimes100
GetScore
GetScoreFromCities
GetScoreFromFutureTech
GetScoreFromGreatWorks
GetScoreFromLand
GetScoreFromPolicies
GetScoreFromPopulation
GetScoreFromReligion
GetScoreFromScenario1
GetScoreFromScenario2
GetScoreFromScenario3
GetScoreFromScenario4
GetScoreFromTechs
GetScoreFromWonders
GetScoreHistory
GetScriptData
GetSeaPlotYield
GetSettlerProductionModifier
GetSpaceProductionModifier
GetSpecialistExtraYield
GetSpecialistProductionModifier
GetStartingPlot
GetStateReligionKey
GetStateReligionName
GetStrikeTurns
GetSwappableGreatArt
GetSwappableGreatArtifact
GetSwappableGreatMusic
GetSwappableGreatWriting
GetTeam
GetTenet
GetTotalFaithPerTurn
GetTotalJONSCulturePerTurn
GetTotalLand
GetTotalLandScored
GetTotalPopulation
GetTotalTimePlayed
GetTourism
GetTourismBonusTurns
GetTourismModifierWith
GetTourismModifierWithTooltip
GetTradeRouteRange
GetTradeRoutes
GetTradeRoutesAvailable
GetTradeRoutesToYou
GetTradeToYouRoutesTTString
GetTradeUnitType
GetTradeYourRoutesTTString
GetTraitCityStateCombatModifier
GetTraitCityUnhappinessMod
GetTraitGoldenAgeCombatModifier
GetTraitGreatGeneralExtraBonus
GetTraitGreatScientistRateModifier
GetTraitPopUnhappinessMod
GetTurnLastPledgeBrokenByMajor
GetTurnLastPledgedProtectionByMajor
GetTurnsSincePlayerBulliedProtectedMinor
GetTurnsSinceThreatenedAnnouncement
GetTurnsSinceThreatenedByBarbarians
GetTurnsToInfluential
GetUnhappiness
GetUnhappinessForecast
GetUnhappinessFromCapturedCityCount
GetUnhappinessFromCityCount
GetUnhappinessFromCityForUI
GetUnhappinessFromCityPopulation
GetUnhappinessFromCitySpecialists
GetUnhappinessFromOccupiedCities
GetUnhappinessFromPublicOpinion
GetUnhappinessFromPuppetCityPopulation
GetUnhappinessFromUnits
GetUnhappinessMod
GetUnimprovedAvailableLuxuryResource
GetUnitBaktun
GetUnitByID
GetUnitClassCount
GetUnitClassCountPlusMaking
GetUnitClassMaking
GetUnitProductionMaintenanceMod
GetUnitProductionModifier
GetUnitProductionNeeded
GetVictoryDisputeLevel
GetWarmongerPreviewString
GetWarmongerThreat
GetWeDeclaredWarOnFriendCount
GetWeDenouncedFriendCount
GetWonderDisputeLevel
GetWonderProductionModifier
GetWorkerSpeedModifier
GetWorstEnemyName
GetWrittenArtifactCulture
GetYieldRateModifier
GreatAdmiralThreshold
GreatGeneralThreshold
HasAvailableGreatWorkSlot
HasBusyMovingUnit
HasBusyUnit
HasCreatedPantheon
HasCreatedReligion
HasOthersReligionInMostCities
HasPolicy
HasReadyUnit
HasReceivedNetTurnComplete
HasRecentIntrigueAbout
HasReligionInMostCities
HasSpyEstablishedSurveillance
HasTurnTimerExpired
HasUnitOfClassType
InitCity
InitUnit
InitUnitWithNameOffset
IsAbleToAnnexCityStates
IsAlive
IsAllies
IsAlwaysSeeBarbCamps
IsAnarchy
IsAngryAboutProtectedMinorAttacked
IsAngryAboutProtectedMinorBullied
IsAngryAboutProtectedMinorKilled
IsAngryAboutSidedWithTheirProtectedMinor
IsAnyGoodyPlotAccessible
IsAnyPlotImproved
IsAskedToStopConverting
IsAskedToStopDigging
IsBarbarian
IsBuildBlockedByFeature
IsBuildingClassMaxedOut
IsBuildingFree
IsCanHurry
IsCanPurchaseAnyCity
IsCapitalCapturedBy
IsCapitalConnectedToCity
IsConnected
IsCurrentResearchRepeat
IsDemandEverMade
IsDenouncedPlayer
IsDenouncingPlayer
IsDoF
IsDoFMessageTooSoon
IsDontSettleMessageTooSoon
IsEmpireSuperUnhappy
IsEmpireUnhappy
IsEmpireVeryUnhappy
IsEverAlive
IsExtendedGame
IsFoundedFirstCity
IsFreeMayaGreatPersonChoice
IsFreePromotion
IsFriendDeclaredWarOnUs
IsFriendDenouncedUs
IsFriends
IsGaveAssistanceTo
IsGoldenAge
IsGoldenAgeCultureBonusDisabled
IsHalfSpecialistUnhappiness
IsHasAccessToHurry
IsHasLostCapital
IsHasPaidTributeTo
IsHasPlayerBulliedProtectedMinor
IsHuman
IsMilitaryFoodProduction
IsMinorCiv
IsMinorCivActiveQuestForPlayer
IsMinorCivContestLeader
IsMinorCivDisplayedQuestForPlayer
IsMinorCivHasUniqueUnit
IsMinorCivRouteEstablishedWithMajor
IsMinorCivUnitSpawningDisabled
IsMinorPermanentWar
IsMinorWarQuestWithMajorActive
IsMyDiplomatVisitingThem
IsNoResearchAvailable
IsNukedBy
IsObserver
IsOption
IsOtherDiplomatVisitingMe
IsPeaceBlocked
IsPlayable
IsPlayerBrokenAttackCityStatePromise
IsPlayerBrokenBorderPromise
IsPlayerBrokenBullyCityStatePromise
IsPlayerBrokenCoopWarPromise
IsPlayerBrokenExpansionPromise
IsPlayerBrokenMilitaryPromise
IsPlayerBrokenNoConvertPromise
IsPlayerBrokenNoDiggingPromise
IsPlayerBrokenSpyPromise
IsPlayerDenouncedEnemy
IsPlayerDenouncedFriend
IsPlayerDoFwithAnyEnemy
IsPlayerDoFwithAnyFriend
IsPlayerForgivenForSpying
IsPlayerHasOpenBorders
IsPlayerHasOpenBordersAutomatically
IsPlayerIgnoredAttackCityStatePromise
IsPlayerIgnoredBorderPromise
IsPlayerIgnoredBullyCityStatePromise
IsPlayerIgnoredExpansionPromise
IsPlayerIgnoredMilitaryPromise
IsPlayerIgnoredNoConvertPromise
IsPlayerIgnoredNoDiggingPromise
IsPlayerIgnoredSpyPromise
IsPlayerNoSettleRequestEverAsked
IsPlayerRecklessExpander
IsPlayerStopSpyingRequestEverAsked
IsPolicyBlocked
IsPolicyBranchBlocked
IsPolicyBranchFinished
IsPolicyBranchUnlocked
IsProductionMaxedBuildingClass
IsProductionMaxedProject
IsProductionMaxedUnitClass
IsProtectedByMajor
IsProtectingMinor
IsProxyWarActiveForMajor
IsResearch
IsResearchingTech
IsSimultaneousTurns
IsSpyDiplomat
IsSpySchmoozing
IsStopSpyingMessageTooSoon
IsStrike
IsThreateningBarbariansEventActiveForPlayer
IsTraitBonusReligiousBelief
IsTurnActive
IsUnitClassMaxedOut
IsUntrustworthyFriend
IsUsingMayaCalendar
IsWhiteFlag
IsWillAcceptPeaceWithPlayer
KillCities
KillUnits
MayNotAnnex
PopResearch
PushResearch
Raze
ReceiveGoody
RemoveBuildingClass
SetAdvancedStartPoints
SetAlwaysSeeBarbCampsCount
SetAnarchyNumTurns
SetBarbarianCombatBonus
SetBaseBuildingGoldMaintenance
SetCombatExperience
SetConscriptCount
SetEmbarkedGraphicOverride
SetFaith
SetFaithPurchaseIndex
SetFaithPurchaseType
SetGold
SetGoldenAgeProgressMeter
SetGreatGeneralCombatBonus
SetHappiness
SetHappinessPerGarrisonedUnit
SetHappinessPerTradeRoute
SetHasPolicy
SetJONSCulture
SetMinorCivUniqueUnit
SetNavalCombatExperience
SetNumFaithGreatPeople
SetNumFreeGreatPeople
SetNumFreePolicies
SetNumFreeTechs
SetNumFreeTenets
SetNumGoldenAges
SetNumMayaBoosts
SetNumPlotsBought
SetNumWondersBeatenTo
SetOption
SetPersonalityType
SetPlayable
SetPolicyBranchUnlocked
SetReplayDataValue
SetResearchingTech
SetScriptData
SetStartingPlot
SpecialistYield
Units
UnitsGoldenAgeCapable
UnitsGoldenAgeReady
UnitsRequiredForGoldenAge
WasResurrectedBy
WasResurrectedThisTurnBy

--]]


